const IslandTemplate = {
  NPCKEYS: [
    "PLAYER",
    "AddisonClark",
    "AndiMcNuttly",
    "BettyLast",
    "BriannaClark",
    "BriggsLast",
    "BrittanyConnors",
    "ChadEllington",
    "ChadLast",
    "CharlieMallard",
    "ChealseaKing",
    "ChristianLumley",
    "ClaraDickson",
    "DaeHoNyguen",
    "DanteVenezia",
    "DarrelEason",
    "DylanMcNuttly",
    "ElaineLast",
    "HenryTurner",
    "JaviLopez",
    "JeanWong",
    "JenSlate",
    "JoeRomano",
    "KarenOMalley",
    "KatieCarrington",
    "KelleighHawk",
    "KennyMcNeil",
    "KonanNoah",
    "KorganLuna",
    "KovaApak",
    "KyleSueco",
    "LauraHale",
    "LennyCarver",
    "LindaLast",
    "LindseyLast",
    "LukasMallard",
    "LynnMcNeil",
    "MaraMcNeil",
    "MarieLast",
    "MarissabelLast",
    "MarkDickson",
    "MateoRomano",
    "MelindaCooper",
    "MikeCarpenter",
    "MitchBrowning",
    "NataliaChenchko",
    "PeteyOBrian",
    "RyderKonieg",
    "ScottAnkor",
    "ShannonDickson",
    "StephanieVenezia",
    "TeddyMcNuttly",
    "WalterMcNeil",
    "WesLast",
  ],
  summarizeResident: (res) => {
    return {
      firstName: res.nameObj.first,
      lastName: res.nameObj.last,
      age: res.age,
      gender: res.gender,
      raceEthnicity: res.details.raceEthnicity,
      descr: res.details.description,
      occupation: res.details.occupation,
      goal: res.details.goals[0].goalDescription,
      appearance: res.appearance,
      CharacterPersonality: res.CharacterPersonality || ["calm"],
    };
  },
  Residents: [
    {
      id: "000000000000000000000001",
      island_id: "66dc506deaae235d2dbe4a3a",
      is_npc: false,
      is_active: true,
      nameObj: {
        first: "Ellie",
        last: "Wigg",
      },
      name: "Ellie",
      age: 28,
      gender: "female",
      details: {
        _id: {
          $oid: "672e7f1c18728437820b7179",
        },
        island_id: "66dc506deaae235d2dbe4a3a",
        character_id: "000000000000000000000001",
        presentingGender: "female",
        raceEthnicity: "white",
        sexualOrientation: "heterosexual",
        occupation: "Crab Fishermen",
        job_id: "672e893418728437820b717d",
        residence_id: "672e893418728437820b717d",
        description:
          "Newest island resident here to take over her estranged fathers crab fishing business after her father passed away.",
        appearance: {
          height: "5ft 6in",
          bodyType: "slim",
          hairColor: "brown",
          hairStyle: "ponytail",
          eyeDescriptor: "large",
          eyeColor: "brown",
          clothingStyle: "dresses and skirts",
        },
        goals: [
          {
            goalType: "Story",
            goalName: "Main Goal",
            goalDescription: "Repair and grow the crab business",
          },
          {
            goalType: "Story",
            goalName: "Secondary Goal",
            goalDescription: "Find a new boyfriend and eventually get married",
          },
        ],
        traits: "672e893418728437820b717d",
        resources_id: "672e893418728437820b717d",
        behavioral_patterns_id: "672e893418728437820b717d",
        special_conditions_id: "672e893418728437820b717d",
      },
    },
    {
      id: "000000000000000000000002",
      island_id: "66dc506deaae235d2dbe4a3a",
      is_npc: true,
      is_active: true,
      nameObj: {
        first: "Addison",
        last: "Clark",
      },
      name: "Addison",
      age: 28,
      gender: "male",
      details: {
        presentingGender: "male",
        raceEthnicity: "white",
        sexualOrientation: "heterosexual",
        occupation: "Hotel Owner",
        description: "Father of Brianna Clark, owner of the Lighthouse B&B.",
        appearance: {
          height: "5ft 11in",
          bodyType: "slim",
          hairColor: "brown",
          hairStyle: "side part",
          eyeDescriptor: "tired",
          eyeColor: "brown",
          clothingStyle: "tux and tie",
        },
        goals: [
          {
            goalType: "Story",
            goalName: "Main Goal",
            goalDescription:
              "Wants to turn the island into a tourism resort destination, even if the island loses its character.",
          },
        ],
        traits: "672e893418728437820b717d",
      },
    },
    {
      id: "000000000000000000000003",
      island_id: "66dc506deaae235d2dbe4a3a",
      is_npc: true,
      is_active: true,
      nameObj: {
        first: "Andi",
        last: "McNuttly",
      },
      name: "Andi",
      age: 32,
      gender: "female",
      details: {
        presentingGender: "male",
        raceEthnicity: "white",
        sexualOrientation: "homosexual",
        occupation: "Harbor Master",
        description: "Runs the Marina and is well known around town.",
        appearance: {
          height: "5ft 10in",
          bodyType: "athletic",
          hairColor: "red",
          hairStyle: "messy hair held up by hat",
          eyeDescriptor: "determined",
          eyeColor: "green",
          clothingStyle: "overalls",
        },
        goals: [
          {
            goalType: "Story",
            goalName: "Main Goal",
            goalDescription: "Expand the Northern Marina",
          },
        ],
        CharacterPersonality: ["Sassy", "witty", "silly"],
        traits: "672e893418728437820b717d",
      },
    },
    {
      id: "000000000000000000000004",
      island_id: "66dc506deaae235d2dbe4a3a",
      is_npc: true,
      is_active: true,
      nameObj: {
        first: "Betty",
        last: "Last",
      },
      name: "Betty",
      age: 30,
      gender: "female",
      details: {
        presentingGender: "female",
        raceEthnicity: "white",
        sexualOrientation: "heterosexual",
        occupation: "Bakery Owner",
        description: "Owner of the local bakery and single.",
        appearance: {
          height: "5ft 4in",
          bodyType: "slim",
          hairColor: "blonde",
          hairStyle: "messy bun",
          eyeDescriptor: "sparkling",
          eyeColor: "blue",
          clothingStyle: "apron and sundresses",
        },
        goals: [
          {
            goalType: "Story",
            goalName: "Main Goal",
            goalDescription:
              "Want's to sell her bakery and move to the main land.",
          },
        ],
        traits: "672e893418728437820b717d",
      },
    },

    {
      id: "000000000000000000000005",
      island_id: "66dc506deaae235d2dbe4a3a",
      is_npc: true,
      is_active: true,
      nameObj: { first: "Brianna", last: "Clark" },
      name: "Brianna",
      age: 19,
      gender: "Female",
      details: {
        id: "000000000000000000000005",
        island_id: "66dc506deaae235d2dbe4a3a",
        img_src: "images/CharacterProfileImages/BriannaClark.png",
        race: "White",
        ethnicity: "",
        sexualOrientation: "Heterosexual",
        occupation: "Receptionist",
        employer: "Medical Clinic",
        job_id: "",
        residence_id: "",
        personalityTraits: "Calm",
        goals: "",
        description: "",
      },
    },
    {
      id: "000000000000000000000006",
      island_id: "66dc506deaae235d2dbe4a3a",
      is_npc: true,
      is_active: true,
      nameObj: { first: "Briggs", last: "" },
      name: "Briggs",
      age: 55,
      gender: "Male",
      details: {
        island_id: "66dc506deaae235d2dbe4a3a",
        img_src: "images/CharacterProfileImages/Briggs.png",
        race: "White",
        ethnicity: "",
        sexualOrientation: "Heterosexual",
        occupation: "Fishing Boat Capt.",
        employer: "Ashley Nicole",
        job_id: "",
        residence_id: "",
        personalityTraits: "Calm",
        goals: "",
        description: "",
      },
    },
    {
      id: "000000000000000000000007",
      island_id: "66dc506deaae235d2dbe4a3a",
      is_npc: true,
      is_active: true,
      nameObj: { first: "Brittany", last: "Connors" },
      name: "Brittany",
      age: 28,
      gender: "Female",
      details: {
        id: "000000000000000000000007",
        island_id: "66dc506deaae235d2dbe4a3a",
        img_src: "images/CharacterProfileImages/BrittanyConnors.png",
        race: "White",
        ethnicity: "",
        sexualOrientation: "BI",
        occupation: "Fitness Instructor",
        employer: "Gym",
        job_id: "",
        residence_id: "",
        personalityTraits: "Calm",
        goals: "",
        description: "twins with lucas and dating chad",
      },
    },
    {
      id: "000000000000000000000008",
      island_id: "66dc506deaae235d2dbe4a3a",
      is_npc: true,
      is_active: true,
      nameObj: {
        first: "Chad",
        last: "Ellington",
      },
      name: "Chad",
      age: 32,
      gender: "male",
      details: {
        presentingGender: "male",
        raceEthnicity: "white",
        sexualOrientation: "heterosexual",
        occupation: "Personal Trainer",
        description: "Owner of the local bakery and single.",
        appearance: {
          height: "5ft 10in",
          bodyType: "athletic",
          hairColor: "brown",
          hairStyle: "gelled hair spiked",
          eyeDescriptor: "determined",
          eyeColor: "blue",
          clothingStyle: "workout",
        },
        goals: [
          {
            goalType: "Story",
            goalName: "Main Goal",
            goalDescription: "Have the lowest BMI and highest bench press",
          },
        ],
        traits: "672e893418728437820b717d",
      },
    },
  ],
};

module.exports = IslandTemplate;
